#
# Default values for Smilr Helm chart
#

# Change to blank string to pull from Docker Hub
registryPrefix: 

# Leave blank if not using DNS with your ingress
domainSuffix: 

# Change if not using AKS with HTTP routing 
ingressClass: addon-http-application-routing

# If using cert-manager to issue TLS certs for HTTPS support 
# Leave blank if you haven't set up cert-manager to disable HTTPS
cmCertIssuer: 

dataApi:
  imageTag: latest
  replicas: 1
  # Leave blank to use the internal service, override if using external database
  mongoConnStr: 
  imagePullPolicy: Always
  
frontend:
  imageTag: latest
  replicas: 1
  imagePullPolicy: Always

sentiment:
  enabled: false
  key: 
  region: westeurope
  image: mcr.microsoft.com/azure-cognitive-services/sentiment:1.1.009301-amd64-preview

mongodb:
  persistence:
    enabled: false
  usePassword: false
  replicaSet:
    enabled: false  