#
# Deploy the back end data API microservice in Kubernetes
# Basic version
#

# ------------------- Deployment ------------------- #

kind: Deployment
apiVersion: apps/v1
metadata:
  name: data-api
  labels:
    app: data-api
    scenario: 1a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-api
  template:
    metadata:
      labels:
        app: data-api
        scenario: 1a
    spec:
      containers:
      - name: data-api-pods

        image: smilr/data-api:stable
        imagePullPolicy: Always

        ports:
        - containerPort: 4000

        env:     
        - name: MONGO_CONNSTR
          value: mongodb://mongodb-svc

        resources:
          limits:
            memory: "256M"
            cpu: "0.25"

--- 

# ------------------- Loadbalancer ------------------- #

kind: Service
apiVersion: v1
metadata:
  name: data-api-svc
  labels:
    scenario: 1a
spec:
  type: LoadBalancer
  # !!! Change this !!!
  loadBalancerIP: 13.93.127.217
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
  selector:
    app: data-api