#
# Deploy the front end microservice which serves the client app
# Basic version
#

# ------------------- Deployment ------------------- #

kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  labels:
    app: frontend
    scenario: 1a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        scenario: 1a
    spec:
      containers:
      - name: frontend-pods

        image: smilr/frontend:stable
        imagePullPolicy: Always

        ports:
        - containerPort: 3000

        env:       
        - name: API_ENDPOINT
          # !!! CHANGE THIS !!! Use the DNS name of your static IP
          value: http://smilr.westeurope.cloudapp.azure.com/api

        resources:
          limits:
            memory: "64M"
            cpu: "0.125"

---

# ------------------- Loadbalancer ------------------- #

kind: Service
apiVersion: v1
metadata:
  name: frontend-svc
  labels:
    scenario: 1a
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: frontend