{
 "title": "RPS Demo",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(request_durations_histogram_secs_count{namespace!=\"\", pod!=\"\"}[1m])))",
     "legendFormat": "requests per second"
    }
   ]
  },
  {
   "title": "RPS Per Pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(irate(request_durations_histogram_secs_count{namespace!=\"\", pod!=\"\"}[1m]))"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(request_durations_histogram_secs_sum / request_durations_histogram_secs_count)",
     "legendFormat": "response time"
    }
   ]
  },
  {
   "title": "Running Pods (VM)",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "max(running_containers_nodes)" }
   ]
  },
  {
   "title": "Running Pods (ACI)",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "max(running_containers_vk)" }
   ]
  }
 ]
}