# Default values for online-store.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

lf:
  image:
    repository: mcr.microsoft.com/virtualnode/samples/live-metrics-forwarder
    tag: latest
    pullPolicy: Always
  service:
      type: ClusterIP
      port: 55678
  resources:
    requests:
      cpu: 500m
      memory: 0.1G

app:
  throttle:
    sleep: 1
    limit: 100

  replicaCount: 1
  image:
    repository: mcr.microsoft.com/virtualnode/samples/online-store
    tag: latest
    pullPolicy: Always
  
  service:
    type: ClusterIP
    port: 80
  
  ingress:
    enabled: true
    # Used to create an Ingress record.
    # When use IP access, comment hosts node
    host: store.f0dfafed36164c7faac0.westeurope.aksapp.io
    annotations:
      kubernetes.io/ingress.class: addon-http-application-routing
  resources:
    requests:
      cpu: 100m
      memory: 0.1G

  nodeSelector: 
    kubernetes.io/role: agent
    beta.kubernetes.io/os: linux
    type: virtual-kubelet

  tolerations: 
  - key: virtual-kubelet.io/provider
    operator: Exists
  - key: azure.com/aci
    effect: NoSchedule

  affinity: {}

promMonitor: online-store

counter:
  replicaCount: 1
  # The interval in seconds
  interval: 5
  # The watcher will report pods on this node separately
  specialNodeName: virtual-node-aci-linux
  image:
    repository: mcr.microsoft.com/virtualnode/samples/container-counter
    tag: latest 
    pullPolicy: Always 

hpa:
  metricTarget: 10
  minReplicas: 1
  maxReplicas: 60

appInsight:
  ## flag to enable App Insight Integration
  enabled: false
  ## Required if enabled; this is the instrumentation key that will be used
  ## for communication with Application Insights. Must be provided
  key:
