kind: Service
apiVersion: v1
metadata:
  name: {{ include "smilr.fullname" . }}-data-api
  labels:
{{ include "smilr.labels" . | indent 4 }} 
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
  selector:
    app.kubernetes.io/name: {{ include "smilr.name" . }}-data-api
    app.kubernetes.io/instance: {{ .Release.Name }}