{{ if (or .Values.dataApi.mongoConnStr .Values.sentiment.key) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "smilr.fullname" . }}-secrets
type: Opaque
data:
  {{ if .Values.dataApi.mongoConnStr }} 
  mongoConnStr: {{ .Values.dataApi.mongoConnStr | b64enc }}
  {{ end }}
  {{ if .Values.sentiment.key }} 
  sentimentKey: {{ .Values.sentiment.key | b64enc }}
  {{ end }}  
{{ end }}
