{{- $fullName := (printf "%s-data-api" (include "smilr.fullname" .)) -}}
{{- $name := (printf "%s-data-api" (include "smilr.name" .)) -}}
{{- $mongoFullName := (printf "%s-mongodb" (include "smilr.fullname" .)) -}}
{{- $sentimentSvcName := (printf "%s-sentiment" (include "smilr.fullname" .)) -}}

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $name }}
    chart: {{ template "smilr.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.dataApi.replicas }}
  selector:
    matchLabels:
      app: {{ $name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ $name }}
 
        image: "{{ .Values.registryPrefix }}smilr/data-api:{{ .Values.dataApi.imageTag }}"
        imagePullPolicy: {{ .Values.dataApi.imagePullPolicy }}

        ports:
        - containerPort: 4000

        env:     
        - name: MONGO_CONNSTR
          value: {{ if .Values.dataApi.mongoConnStr }} {{ .Values.dataApi.mongoConnStr }} {{ else }} "mongodb://{{ .Release.Name }}-mongodb" {{ end }}

        - name: RELEASE_INFO
          value: 'Helm release: {{ .Release.Name }}, namespace: {{ .Release.Namespace }}, revision: {{ .Release.Revision }}, chart: {{ .Chart.Name }}-{{ .Chart.Version }}'

        {{ if .Values.sentiment.enabled }}
        - name: SENTIMENT_API_ENDPOINT
          value: http://{{ $sentimentSvcName }}:5000
        {{ end }}

        livenessProbe:
          httpGet:
            path: /api/info
            port: 4000
          initialDelaySeconds: 3
          periodSeconds: 20

        resources:
          limits:
            memory: "256M"
            cpu: "0.125"
