{{- $fullName := (printf "%s-frontend" (include "smilr.fullname" .)) -}}
{{- $name := (printf "%s-frontend" (include "smilr.name" .)) -}}

kind: Service
apiVersion: v1
metadata:
  name: {{ $fullName }}
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: {{ $name }}
    release: {{ .Release.Name }}