kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "smilr.fullname" . }}-frontend
  labels:
{{ include "smilr.labels" . | indent 4 }} 
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "smilr.name" . }}-frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "smilr.name" . }}-frontend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ include "smilr.name" . }}

        image: "{{ .Values.registryPrefix }}smilr/frontend:{{ .Values.frontend.imageTag }}"
        imagePullPolicy: {{ .Values.frontend.imagePullPolicy }}

        ports:
        - containerPort: 3000

        env:
        - name: API_ENDPOINT
          value: {{ if .Values.ingress.domainSuffix }} "/api"  {{ else }} "/{{ .Release.Name }}/api" {{ end }}

        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 20

        resources:
          requests:
            memory: "64M"
            cpu: "0.1"