{{- $tlsEnabled := (or .Values.ingress.certIssuer .Values.ingress.certName) -}}

{{ if .Values.ingress.domainSuffix }}
#
# Ingress for host based routing, release name prefixed 
#
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "smilr.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    {{ if .Values.ingress.certIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certIssuer }}
    {{ end }}
    {{ if $tlsEnabled }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{ else }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{ end }}
  labels:
{{ include "smilr.labels" . | indent 4 }}
spec:
  {{ if $tlsEnabled }}
  tls:
  - hosts:
    - "{{ include "smilr.fullname" . }}.{{ .Values.ingress.domainSuffix }}"
    {{ if .Values.ingress.certName }}
    secretName: {{ .Values.ingress.certName }}
    {{ else }}
    secretName: {{ include "smilr.fullname" . }}
    {{ end }}
  {{ end }}
  rules:
  - host: "{{ include "smilr.fullname" . }}.{{ .Values.ingress.domainSuffix }}"
    http:
      paths:
      - path: /api
        backend:
          serviceName: {{ include "smilr.fullname" . }}-data-api
          servicePort: 80
      - path: /api-docs
        backend:
          serviceName: {{ include "smilr.fullname" . }}-data-api
          servicePort: 80          
      - path: /
        backend:
          serviceName: {{ include "smilr.fullname" . }}-frontend
          servicePort: 80

{{ else }}
#
# Ingress for path URL based routing, no DNS required only ingress IP
#
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ include "smilr.fullname" . }}-data-api"
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: "/api"
spec:
  rules:
  - http:
      paths:
      - path: "/{{ .Release.Name }}/api"
        backend:
          serviceName: {{ include "smilr.fullname" . }}-data-api
          servicePort: 80
      - path: "/{{ .Release.Name }}/api-docs"
        backend:
          serviceName: {{ include "smilr.fullname" . }}-data-api
          servicePort: 80
          
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ include "smilr.fullname" . }}-frontend"
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/add-base-url: "true"
spec:
  rules:
  - http:
      paths:
      - path: "/{{ .Release.Name }}"
        backend:
          serviceName: {{ include "smilr.fullname" . }}-frontend
          servicePort: 80    
{{ end }}
