{{- $frontendFullName := (printf "%s-frontend" (include "smilr.fullname" .)) -}}
{{- $dataApifullName := (printf "%s-data-api" (include "smilr.fullname" .)) -}}
{{- $ingressName := (printf "%s-ingress" (include "smilr.fullname" .)) -}}
{{- $certName := (printf "%s-cert" (include "smilr.fullname" .)) -}}

{{ if .Values.domainSuffix }}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ $ingressName }}"
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressClass }}
    {{ if .Values.cmCertIssuer }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    certmanager.k8s.io/cluster-issuer: {{ .Values.cmCertIssuer }}
    {{ else }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{ end }}
spec:
  {{ if .Values.cmCertIssuer }}
  tls:
  - hosts:
    - "{{ .Release.Name }}.{{ .Values.domainSuffix }}"
    secretName: "{{ $certName }}"
  {{ end }}
  rules:
  - host: "{{ .Release.Name }}.{{ .Values.domainSuffix }}"
    http:
      paths:
      - path: /api
        backend:
          serviceName: {{ $dataApifullName }}
          servicePort: 80
      - path: /
        backend:
          serviceName: {{ $frontendFullName }}
          servicePort: 80

{{ else }}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ $ingressName }}"
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressClass }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: "/api"
spec:
  rules:
  - http:
      paths:
      - path: "/{{ .Release.Name }}/api"
        backend:
          serviceName: {{ $dataApifullName }}
          servicePort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ $ingressName }}-front"
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressClass }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/add-base-url: "true"
spec:
  rules:
  - http:
      paths:
      - path: "/{{ .Release.Name }}"
        backend:
          serviceName: {{ $frontendFullName }}
          servicePort: 80    
{{ end }}
