trigger:
- master

#
# 1st job runs on Hosted VS2017
# - Builds/compiles the project, copies files and uploads
#
jobs:
  job: buildDotnet
  displayName: 'Dotnet Project Build'

  variables:
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

  pool:
    name: Hosted VS2017
    demands:
    - msbuild
    - visualstudio

  steps:
  - task: NuGetInstaller@0
    displayName: 'NuGet restore **\*.sln'
    inputs:
      solution: '**\*.sln'

  - task: VSBuild@1
    displayName: 'Build solution **\*.sln'
    inputs:
      vsVersion: 14.0
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'

  - task: CopyFiles@1
    displayName: 'Copy main website output'
    inputs:
      SourceFolder: Contoso.Apps.SportsLeague
      Contents: |
      App_Start\**
      bin\**
      fonts\**
      Images\**
      Scripts\**
      Styles\**
      Views\**
      favicon.*
      Global.*
      Web.config
      TargetFolder: '$(build.artifactstagingdirectory)/website/'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: contoso

  #
  # 2nd job runs on Windows 2019 with VS2019
  # - Downloads artifacts and builds image from Dockerfile
  #
  job: buildDocker
  displayName: 'Docker Image Build & Push'
  dependsOn: buildDotnet

  variables:
    container-registry: 'bcdemo'

  pool:
    name: Hosted Windows 2019 with VS2019

  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      artifactName: contoso

  - task: Docker@2
    displayName: 'Build image from Dockerfile'
    inputs:
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      buildContext: '$(System.ArtifactsDirectory)/contoso'
      containerRegistry: '$(container-registry)'
      repository: contososports
      tags: |
      $(Build.BuildId)
      latest
