apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{change-me}}-cert
  namespace: default
spec:
  secretName: {{change-me}}-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: '*.{{change-me}}'
  dnsNames:
  - '*.{{change-me}}'      