apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # You must replace this email address with your own.
    email: dummy@example.net
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: letsencrypt-staging-key

    # Add a single challenge solver, HTTP01 using http-application-routing addon
    solvers:
    - http01:
        ingress:
          class: addon-http-application-routing