apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-dns
spec:
  acme:
    # You must replace this email address with your own.
    email: dummy@example.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: letsencrypt-prod-dns-key
    solvers:
    - dns01:
        azuredns:
          # Service principal clientId (also called appId)
          clientID: {{change-me}}
          # A secretKeyRef to a service principal ClientSecret (password)
          # !IMPORTANT! Create secret 'azuredns-config' in same namespace as cert-manager pods
          clientSecretSecretRef:
            name: azuredns-config
            key: CLIENT_SECRET
          # Azure subscription Id
          subscriptionID: {{change-me}}
          # Azure AD tenant Id
          tenantID: {{change-me}}
          # ResourceGroup name where dns zone is provisioned
          resourceGroupName: {{change-me}}
          hostedZoneName: {{change-me}}
          # Azure Cloud Environment, default to AzurePublicCloud
          environment: AzurePublicCloud