apiVersion: v1
items:
- apiVersion: autoscaling/v2beta2
  kind: HorizontalPodAutoscaler
  metadata:
    creationTimestamp: "2019-05-12T11:00:10Z"
    name: nodeapp
    namespace: default
    resourceVersion: "4042"
    selfLink: /apis/autoscaling/v2beta2/namespaces/default/horizontalpodautoscalers/nodeapp
    uid: 1c5ab5de-74a5-11e9-902c-be9c4ca670f9
  spec:
    maxReplicas: 10
    metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
      type: Resource
    minReplicas: 1
    scaleTargetRef:
      apiVersion: extensions/v1beta1
      kind: Deployment
      name: nodeapp
  status:
    conditions:
    - lastTransitionTime: "2019-05-12T11:00:25Z"
      message: the HPA controller was able to get the target's current scale
      reason: SucceededGetScale
      status: "True"
      type: AbleToScale
    - lastTransitionTime: "2019-05-12T11:00:25Z"
      message: 'the HPA was unable to compute the replica count: unable to get metrics
        for resource cpu: no metrics returned from resource metrics API'
      reason: FailedGetResourceMetric
      status: "False"
      type: ScalingActive
    currentMetrics: null
    currentReplicas: 2
    desiredReplicas: 0
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
