apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: contoso-ingress
  labels:
    scenario: "8"
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  # !!! Change host as required to match your DNS configuration
  - host: contoso.{{CHANGEME}.{{CHANGEME}}.aksapp.io
    http:
      paths:
      - path: /
        backend:
          serviceName: contoso-svc
          servicePort: 80
